In [65]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from utils import Util
from steps.remi_controls import _calculate_pums_rates

util = Util('configs_pypyr')

In [66]:
with pd.HDFStore('data/pipeline.h5') as store:
    tables = store.keys()
tables

['/county_controls',
 '/industry_crosswalk',
 '/occupation_crosswalk',
 '/pums_households_prepared',
 '/pums_person_prepared',
 '/region_summed',
 '/region_summed_2050',
 '/region_summed_2060',
 '/regional_controls',
 '/remi',
 '/remi_ind',
 '/seed_households',
 '/seed_persons',
 '/seed_persons/meta/values_block_0/meta',
 '/seed_households/meta/values_block_0/meta',
 '/pums_person_prepared/meta/values_block_0/meta',
 '/pums_households_prepared/meta/values_block_0/meta']

In [82]:
remi_summed = util.get_table('region_summed')
remi_summed

    variable     2060
0  total_pop  5968250
1      hhpop  5844314
2         hh  2449926
3         gq   123937

In [106]:
remi_ind = util.get_table('remi_ind')

                  variable     2060
0                total_pop  5968250
1                    hhpop  5844314
2                       hh  2449926
3                       gq   123937
0      military_employment    45070
1  non_military_employment  3982484
2               employment  4027553

In [101]:
remi_ind['industry'] = np.where(remi_ind['industry'] == '99', '98', remi_ind['industry'])

In [104]:
remi_ind = remi_ind.groupby(['county_id','industry']).agg({'employment':'sum'}).reset_index()

In [105]:
remi_ind

    county_id industry     employment
0       53033       11    5988.153404
1       53033       21    1475.306935
2       53033       22    2617.059710
3       53033       23  146823.589708
4       53033     3133  120954.768792
..        ...      ...            ...
75      53061       62   66502.281619
76      53061       71   11932.880735
77      53061       72   38599.246087
78      53061       81   30915.931721
79      53061       98   54431.490595

[80 rows x 3 columns]